### ISSUE TITLE
Add integrated support to submit Forms using AJAX

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout-forms#344]

**Comment by nicholashu** [comment]
I do this all the time. Craft 3 Headless, Next.js

`SproutForm.ts`
```export default class SproutForm {
public static async sendForm(formData: FormData) {
    const response = await this.submit(formData);
    if (response.errors) {
      return response;
    }
    return response;
  }

  private static async submit(formData: FormData) {
    try {
      const response = await fetch('/sproutForms/entries/saveEntry', {
        method: 'POST',
        credentials: 'same-origin',
        headers: {
          'X-Requested-With':'XMLHttpRequest',
          Accept: 'application/json'
        },
        body: formData,
      }).then(r => r.json());
      return response;
    } catch (error) {
      # DO SOMETHING WITH ERROR
    }
  }
}
```

`formpage.ts`
```
async function handleSubmit(values) {
    const csrfToken = await functionToGetCsrf();
    const formData = new FormData();
    Object.keys(values).forEach(key => formData.append(`fields[${key}]`, values[key] == null ? '' : values[key]));
    formData.append('action', ''sprout-forms/entries/save-entry'');
    formData.append('handle', 'FORM-HANDLE-IN-SPROUT');
    formData.append('CRAFT_CSRF_TOKEN', csrfToken);

    const response = await SproutForm.sendForm(formData);
    if (response.success) {
      #DO SOMETHING WITH SUCCESS
    } else {
      #DO SOMETHING WITH ERROR
    }
  }
```

`modules/csrf/controllers/CsrfController.php`
```
<?php
namespace csrf\controllers;

use Craft;
use craft\web\Controller;

class CsrfController extends Controller
{
    public $allowAnonymous = ['csrf'];

    public function actionCsrf()
    {
        return Craft::$app->getRequest()->csrfToken;
    }
}
```

**Comment by BenParizek** [comment]
Thanks for the example @nicholashu

**Comment by Jones-S** [comment]
@nicholashu Thanks for your example. I had this running with craft where it did not yet support a headless setup.
I forked sproutforms and made some hacky adaptations, I see you have it solved nicely though.

I also struggled getting that CSRF token to my frontend, but I see that you have a function doing that.
Are you using something like a `Netlify Function` or similar do get that token from a headless craft installation (maybe on another domain) to your frontend?

It would be super helpful to get some insight, what your `functionToGetCsrf` does.
Thanks for sharing 👍 and any other helpful thoughts.

Cheers

**Comment by nicholashu** [comment]
@Jones-S `functionTOGetCsrf` is just a fetch request that sends a GET request to the CsrfControllers Csrf action (in the last example code block). 

However, I have since improved this process and the Csrf module is no longer needed. It turns out craft's session info API gives you a CSRF token you can use.

`csrf.ts`

    export default class CSRF {
	  static getCsrf = async () => {
	     try {
		const session = await fetch('/api/users/session-info', { headers: { 'Accept': 'application/json' } }).then(response => response.json());
		if (session?.csrfTokenValue) {
		  return session.csrfTokenValue;
		 }
		return ;
	     } catch (e) {
		doSomethingWithError(e);
	     }
       }
    }
				
nginx determines how routes are handled
`site.conf`
```
  location / {
      proxy_pass http://127.0.0.1:3000; // node
  }
    
   location ^~ /api {
      try_files $uri $uri/ /index.php?$query_string; // craft
  }
```

`routes.php`
```
return [
    'api/users/session-info' => 'users/session-info',
    ...lots of other routes
]
```

**Comment by Jones-S** [comment]
Thanks for sharing!
Just for clarification: I read that you don't need cookies. (in #436) but as far as I understand:

> With CSRF protection enabled, all of your site’s visitors will get a “CRAFT_CSRF_TOKEN” cookie set on their browser, and all POST requests must be accompanied by a POST parameter with a matching name and value (the CSRF Token).
https://craftcms.com/knowledge-base/enabling-csrf-protection

I will only be able to make a POST request if that token matches the things saved in the cookie. 
Or with what value is your CSRF token compared with?

Thanks for some more help 😅

**Comment by nicholashu** [comment]
calling `users/session-info` returns an object with `csrfTokenValue`. Add that value to the body of your POST to `/sproutForms/entries/saveEntry`

e.g.,
`formData.append('CRAFT_CSRF_TOKEN', csrfToken);` 
just like in my original comment

The CSRF token provided is valid for the current users session, it's just not stored in cookies as I am using craft in headless mode. I've used this method to provide basic user authentication in headless mode too as `user/session-info` returns whether the user is a guest or logged in.

**Comment by Jones-S** [comment]
Alright. I see. Thanks for your help. I now need to solve some CORS issues, because I can't even send the post request, due to missing `Allow-Origin` headers. I think I do understand the CSRF token stuff though. So thanks a lot for your (very quick) help. Much appreciated.

**Comment by BenParizek** [comment]
While I'll need more time before I can get it into a release, I've posted a potential update that can be made to add support for Allow-Origin headers via an event or temporary hack if anybody needs to address this in the meantime:
https://github.com/barrelstrength/craft-sprout-forms/issues/528#issuecomment-685922801

**Comment by BenParizek** [comment]
Cleaning up old tasks. Support has been added for this a while ago using the Async Submission Method setting.
