### ISSUE TITLE
Checkboxes not validating in accessible forms

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/sprout-forms#429]
### Description
I want to validate a checkbox group.
I have copied the checkbox template from the accessible form templates and added some minor changes (added a class and a span to the label, nothing more) but it's not validating.

According to a previous bug report of mine (#336) this should work out of the box?
But the checkboxes keep validating on their own (browser validation, not Sprout validation as that kicks in first but it should be handled by Sprout JavaScript). 

### Steps to reproduce

1. Create a form with a checkbox field
2. Try validating 1 checked field

### Additional info

- Craft version: 3.4.71
- PHP version: 7.3
- Database driver & version:  MySAL
- Plugins & versions: 3.8.3

**Comment by BenParizek** [comment]
@TomDeSmet Can you confirm what templates you are using? Is this a bug with the default Accessible Templates or did you add the default Javascript to custom templates and it's not working in custom templates?

**Comment by TomDeSmet** [comment]
I'm using the default accessible templates (but overriding them because I need to add some classes to some fields).

But I'm not using any custom templates that output my form.

**Comment by BenParizek** [comment]
@TomDeSmet This is working in my tests so I think I'll need to better understand what you are overriding to try to recreate.

One way to troubleshoot this would be to revert to using solely the default templates to confirm the checkbox logic still works for you, and then compare the default templates to the updates you've made to see where there might be a difference.

The javascript that manages the required checkbox validation requires a few things:

Checkbox Fields are identified by an HTML element that has the `.checkboxes.required` classes.

```
this.requiredCheckboxFields = document.querySelectorAll('.checkboxes.required');
```
Can you confirm your templates are outputting the `checkboxes` and `required` classes on the Checkboxes field `<fieldset>` or some related element that wraps the Checkbox input fields? I

That would be handled by this line in the `field.twig` template:

```
<{{ fieldHtmlTag }}
        {%- if id %} id="{{ id }}-field"{% endif %} class="field {{ field.getFieldInputFolder() }}
        {%- if class %} {{ class }}{% endif -%}
        {%- if fieldCssClasses %} {{ fieldCssClasses }}{% endif -%}
        {%- if errors %} {{ errorClass }}{% endif -%}
        {%- if required %} required{% endif -%}
        ">
```
