### ISSUE TITLE
Update search indexes error

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/sprout-forms#502]
### Description (screenshots, logs, ...)
Same error as #425 but now present in 3.12.2 but on a different code block:

```
session_set_cookie_params(): Cannot change session cookie parameters when headers already sent 
```

```
{
    "elementType": "barrelstrength\\sproutforms\\elements\\Entry",
    "elementId": 22654,
    "siteId": "3",
    "fieldHandles": [
        "toEmailAddresses",
        "singleLine1",
        "surname",
        "email",
        "phone",
        "questionTopicEmail",
        "question",
        "privacyPolicyOptIn"
    ],
    "description": null
}
```

**Comment by exophunk** [comment]
This happens for me as well in 3.12.2. All search index update jobs fail. I nailed it down to be the same issue as #376  with accessing session when running a search index update job.

it still crashes in barrelstrength/sprout-forms/src/fields/formfields/Invisible.php

Line 169: `$invisibleValue = Craft::$app->getSession()->get($this->handle);`

If you just put the whole thing (like 169 to 177) in a try catch block, that would solve it.

Also if this is possible, sprout form entries could be removed from the search index completely.

**Comment by krizzzly** [comment]
its possible to surpress updating the search index inside the plugin:
`vendor/barrelstrength/sprout-forms/src/services/Entries.php:164`

`            $success = Craft::$app->getElements()->saveElement($entry,true,true,false);`

The last parameter tells NOT to update search indexes on entry savings.

**Comment by BenParizek** [comment]
Thanks @krizzzly. @TomDeSmet @exophunk if you can use the above workaround for now, we're currently focused on getting a release out to support Craft 3.5 and will plan to roll this fix into that next release.

**Comment by exophunk** [comment]
This bug is open since june and was not included in any of the last releases.

Will you fix this in a next release? it's a one-line code change, see krizzly's comment

**Comment by BenParizek** [comment]
@exophunk Sorry for the delay. This should be addressed in a release soon. I'm working through addressing several structural issues that have been leading to some recurring migration problems. Once I get through that milestone in cleaning that up I'll be able to address these issues more quickly again and I'll update here as soon as I have this out in a tagged release.

**Comment by BenParizek** [comment]
@krizzzly. @TomDeSmet @exophunk Do any of you have a step by step example of how to recreate this? And an example of what value you are using in the Invisible Field?

I'm currently unable to recreate this using an Invisible field in a Form layout that captures a static value or dynamic value based on another field in the form and submitting the form via the front-end or back end. I'd like to avoid using the solution proposed above as it would make the search feature less useful for those who want to use it and it currently appears we are already not running the code on line 169 during console requests:

https://github.com/barrelstrength/craft-sprout-forms/blob/97e59219357826b025feb79b8a98d65a476c88b5/src/fields/formfields/Invisible.php#L168-L178

So it's currently unclear to me how that line is getting triggered to cause the problem.
