### ISSUE TITLE
Install failing -> Table 'craft_sproutforms_forms' already exists

### ISSUE THREAD

**Issue by Chris-esser** [barrelstrength/sprout-forms#578]
I attempted to upgrade sprout forms to v3.13.5. 
Craft Control panel shows install failed.
web.log shows: 
-------------
2021-06-23 21:41:06 [-][20110][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.016s). Output:
    > create table {{%sproutforms_forms}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_sproutforms_forms' already exists
The SQL being executed was: CREATE TABLE `craft_sproutforms_forms` (
---------------
How do I get past this error?

**Comment by BenParizek** [comment]
@Chris-esser The error suggests that either you may have tried to upgrade once and failed and tried again or that we may have a bug somewhere in our migration code that doesn't check if a table exists. 

If you are still having issues with this, and can rule out the first scenario, can you provide any additional info from the error logs on the second scenario such as which file and line of code is throwing the error?

**Comment by Chris-esser** [comment]
Hi Ben,
Yes, I believe there was a previous attempt to upgrade and then we rolled back.

Is there a solution for this? Is it as simple as dropping the table and running the upgrade?

Chris Esser
Deloitte Services LP
Tel/Direct: +1 (615) 882 - 6067
www.deloitte.com

From: Ben Parizek ***@***.***>
Sent: Thursday, July 1, 2021 6:52 AM
To: barrelstrength/craft-sprout-forms ***@***.***>
Cc: Esser, Chris ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [barrelstrength/craft-sprout-forms] Install failing -> Table 'craft_sproutforms_forms' already exists (#578)


@Chris-esser<https://secure-web.cisco.com/1ebnlqum51_x_GQhiR8Kmrb7VWDWxIJ2UlNMwUC8nwF6qYkdVhGPt1cWCtWofVdXHbwC_zEFg7DZmBPU7JcK-ukMUscmBJywkRWVzOJ0lX7f02m87C1bE1QRxE34JHg9WMvKqR2YEfjA_2GaK9H7qrhGfSD1Tq1rPgKbi1WDAN3GhumRSmTcUYJfFXuSE1mV828xUNyLZff0l6G4E9AIJIgnAPtMWd_qNMvzCZc1ltBYyn9EmIvAxZv3q7nLPFqcPLd5OiS0uzjcKNK7LC4Yuc5sTDYAPoUNnX52qabdvHWLjKRLyYx-iqCXN-Pq-4NifK0_6utlIUWhn3-Q3jQoGhbFEqury8a4ybmXTiVvo1g240Uyo78zxxmpQS-AgJwhMtLZ7z8oz5n98YbpxnzRhoOpG-NCg4dZffnF-ewqA4G7sHbRqt00xRCA4vC5sZWoTR43LlYlkP7AG_fukTsBB8XSep5LLe8k2TPJECXVIEYukdhzDUpYy4UrOJ8w3F44Ym7PNK_RJ6LZ3Qp0pyGKk2w/https%3A%2F%2Fgithub.com%2FChris-esser> The error suggests that either you may have tried to upgrade once and failed and tried again or that we may have a bug somewhere in our migration code that doesn't check if a table exists.

If you are still having issues with this, and can rule out the first scenario, can you provide any additional info from the error logs on the second scenario such as which file and line of code is throwing the error?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1QezH5YATqWWicz4BrWMGxLloJQzI2AuB4BlhCkgkcGoOnqGUt3C_towJMwbMobIGX_pv_DCvhG0syREGBT0mEFASqsTBCcikrb1VJKSnvGVwriG2v4Dh47iN8JgyePJMAU1sebR3uBq76XawoPJPe1PGd0tPUc4EpUs_IDgYQOBfZ5lLeKUd5xw2yrNEBnItGw-9pj8RnELcIvwNVasahlp90CsJd_8Wh9hCuj8-4RZ7E3pDUUCbzVkRCC3bdEb0bgqbGFKWOyuqo8MLlpqCZUCCk6tffvV_68Ifz4G80GZH6UfkvfGqxUOHZ8gNVmGsqRYGqQ2vkU4UaOHHfWl1zUhgX0Jleub16cFDbtbE6GqGlGAmnZbsnWS_zcEy7fQBPBSqXBPFswQlFqelv1ntYZ8TV1-kXAdwbOU27kXwnu84fGRwCV1_Sxb3zceN9awAOt7h8tXvTmkaHChubrvM-_AnaKdxSC7E1LVgUJ897MOdvXCmTEbPbyS-GM6wFMyGwQ4qxxxBzRRXibAfpx1BBg/https%3A%2F%2Fgithub.com%2Fbarrelstrength%2Fcraft-sprout-forms%2Fissues%2F578%23issuecomment-872179559>, or unsubscribe<https://secure-web.cisco.com/1Spx_mtLqGmDc9Fzet6bROX0sqBHS1l1BX0eFArmj7LT6QjxfRLGWv3riyqnG17hm7mz1WATIHVcHOzQAUZNyjR3Yd6Ipu5GGEqmd-sTr5JpfcDI-5LM2FTZP0Kmem7aYxrgUF03VtVzsmlCyOn6DKTgm24vMx1eF4EqCh-G3I1IVc9AvwesL4BhDfteo8-lTSXqT54cDCJ_48myGB4gH1D0-MAGm10VgnfPrjtBviP_vrHaWJtIfB1Xk2PJMoU-qXmbkBWV7NzcFQZCmMrntgwNwX8yr3SqzCNAt9sKReLLaT6QIfi9RINu-VdthSge5qV7H6F23CKDeOIXhblgVFZHYtIAf8vQbaUwYfee42__TcKlL8DR6vLqm0aVz_q9xr3Ipaxx0k9vhFy2ChXxb7zjj1Ej_nf_mZhx9BvAFh1dlP4Uy1WrsunvQNgVCX-nuOkP321NGFVX89TWH3BQv1PApZY13TGTECK2t9wlYNMHl2eWjdBliq61BI7o_bvxb4klZsCP4wLoLT1x4F_Sm-w/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANQ45FJ2QRVL5DHRKPFL5GTTVRJEFANCNFSM47GVIYDQ>.

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and any disclosure, copying, or distribution of this message, or the taking of any action based on it, by you is strictly prohibited.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

v.E.1

**Comment by BenParizek** [comment]
@Chris-esser It really depends the data you are working with that you need to preserve. If you can trigger a new upgrade with the old database, that of course is the best option. If you've already upgraded and this remains a thing, you'll need to evaluate what data you need to keep or potentially hack the migration code to do something it's not doing. It's hard to say until we figure out which part of the code is throwing the error.

If you'd like to walk through it on a screen share, I can offer more specific thoughts:
https://barrelstrengthdesign.com/schedule/ben-parizek/
